### ISSUE TITLE
Error: "Cannot flatten a non-CID font"

### ISSUE THREAD

**Issue by djvs** [coolwanglu/pdf2htmlEX#455]
https://github.com/coolwanglu/pdf2htmlEX/blob/master/src/util/ffw.c 

Produced in the code here.  Maybe 5-10% of real-world textbook PDFs run into this error. As I understand these are TTF/OpenFont fonts (?) - is there a way to fix this, in pdf2htmlEX itself? What is the "flattening" exactly?

**Comment by Sequa** [comment]
I ran into the same problem. The PDF can be found here: http://openstaxcollege.org/textbooks/college-physics/pdf (I tried the low resolution version). Would appreciate if you could look into this. Thanks

**Comment by djvs** [comment]
http://djvs.co/4-Energy+and+cells.pdf Another failing PDF available here.

**Comment by coolwanglu** [comment]
Just fixed in `incoming`.

**Comment by djvs** [comment]
I am still getting this with a fresh pull + build from incoming

**Comment by coolwanglu** [comment]
I'll test again.

**Comment by djvs** [comment]
Pdf producing error: http://djvs.co/ch1.pdf

**Comment by djvs** [comment]
Wait, sorry.  Think it was my error

**Comment by djvs** [comment]
Yup, my apologies, it's good.

**Comment by coolwanglu** [comment]
OK.

**Comment by sledorze** [comment]
Do you know when it will be part of an official release?

**Comment by ericlenio** [comment]
2nd request for an official release.

**Comment by lyphandl** [comment]
My problem:
Preprocessing: 472/472
Cannot flatten a non-CID font

-> I using pdf2html version 13.6 lates
pdf2htmlEX version 0.13.6
Copyright 2012-2014 Lu Wang <coolwanglu@gmail.com> and other contributors
Libraries: 
  poppler 0.26.3
  libfontforge 20150130
  cairo 1.12.0
Default data-dir: /usr/local/share/pdf2htmlEX
Supported image format: png jpg svg

?

**Comment by IvanSolovjev** [comment]
When do you plan to release this fix?

**Comment by coolwanglu** [comment]
@IvanSolovjev Did the `master` branch not work for you?

**Comment by IvanSolovjev** [comment]
No, it doesn't work for some files. 
I used <b>pdf2htmlEX --embed cfijo --split-pages 1 366.pdf</b> command.
pdf2htmlEX shows error message and stop execution if I'm using ubuntu console command. 
But if I try to execute same command via PHP <a href="http://php.net/manual/en/function.shell-exec.php">shell_exec</a>, pdf2htmlEX send error message to logs, but shell_exec function continue execution. Could it be caused that pdf2htmlEX doesn't close correctly?

File example: <a href="https://drive.google.com/file/d/0B_15KW9pfyAJdGptSG00VXQ5VEU/view?usp=sharing">Google Drive link</a>

**Comment by haydenbleasel** [comment]
@coolwanglu Reading this as I'm getting the same error on the stable version through Brew. Tried installing master branch instead (`brew install pdf2htmlex --HEAD`) but unfortunately:

```
...
==> Patching
patching file 3rdparty/poppler/git/CairoFontEngine.cc
Hunk #1 FAILED at 421.
1 out of 1 hunk FAILED -- saving rejects to file 3rdparty/poppler/git/CairoFontEngine.cc.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1
```

Not sure if this is a pdf2htmlEX issue or Homebrew though. Currently looking around.

**Comment by haydenbleasel** [comment]
@coolwanglu Update: Homebrew is still referencing `pdf2htmlEX@0.13.6` rather than `pdf2htmlEX@0.14.6` and therefore doesn't have the fix to this.
